apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
  namespace: pf
  labels:
    app: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        image: himjain/ping:1.0
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
            memory: "256Mi" 
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"

---

apiVersion: v1
kind: Service
metadata:
  name: ping
  namespace: pf
  labels:
    app: ping
spec:
  selector:
    app: ping
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

# ---

# apiVersion: networking.istio.io/v1beta1
# kind: VirtualService
# metadata:
#   name: ping-vs
#   namespace: pf
# spec:
#   gateways:
#   - istio-system/default-gateway
#   hosts:
#   - ping.himajai2-32.test.thunderhead.io
#   http:
#   - match:
#     - uri:
#         prefix: /ping
#     route:
#     - destination:
#         host: ping.pf.svc.cluster.local
#         port:
#           number: 5000

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ping-alb-vs
  namespace: pf
spec:
  gateways:
  - istio-system/default-gateway-alb
  hosts:
  - ping-alb.himajai2-32.test.thunderhead.io
  http:
  - match:
    - uri:
        prefix: /ping
    route:
    - destination:
        host: ping.pf.svc.cluster.local
        port:
          number: 5000

---